# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Acasă
    url: /#top
    weight: 10
  - name: Soluții
    url: /#solutions
    weight: 20
  - name: Resurse
    weight: 30
    hasChildren: true
#  - parent: Resurse
#    name: Vizualizări
#    url: blog/
