# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'SRL'
    org_name: 'DigitalComp'
    description: 'Analiza Datelor și Data Science'
    twitter: 'DigitalComp'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    logo:
      text: "DigitalComp"
      # Logo filename in `assets/media/` folder
      filename: ""
    button:
      enable: true
      text: "Ofertă"
      url: "https://us17.list-manage.com/contact-form?u=ce7b84d5afafae77b846a44ef&form_id=90c9a9b298b5653866f49e8b9f2d6d9e"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} DigitalComp'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
